### ISSUE TITLE
Naming of Reference object

### ISSUE THREAD

**Issue by computron** [hackingmaterials/jobflow#2]
I don't think Reference is an optimal naming, just because it is very generic.

How about something like OutputRef? or OutputProxy?

Just to make it clear that this is connected to the Output object

**Comment by davidwaroquiers** [comment]
What about "Link" or "OutputLink" ?

**Comment by computron** [comment]
I like having "Output" in there ... don't have much preference between OutputRef, OutputProxy, OutputReference, or OutputLink. I would say OutputReference feels a bit too long, but since this object is not going to be instantiated or seen directly by the user very much the length may not be such a problem.

**Comment by utf** [comment]
Done. I went with `OutputReference`.
